---
- hosts: all
  become: true
  tasks:
  - name: Update Servers
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install Apache2
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
      state: latest 

  - name: Set Timezone (Africa/Lagos)
    tags: time
    timezone: name=Africa/Lagos

  - name: Display hostname on server
    tags: printf
    shell: echo "<h1>Welcome, I am $(hostname -f)</h1>" > /var/www/html/index.html
 
  - name: Restart Apache2
    tags: restart
    service:
      name: apache2
      state: restarted
